#!/bin/bash
if [[ "${DEBUG}" == "true" ]]; then
  set -x
fi

ID=${ID:-''}
ID_DIR="/tmp/logs/${ID}"
ORG=${ORG:-''}
GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN:-''}
API_URL_PREFIX=${API_URL_PREFIX:-'https://api.github.com'}
TEAMS_FILE="${ID_DIR}/teams.json"
IMPORT_FILE=/opt/resources/imports_teams.txt

if [ -f "${IMPORT_FILE}" ]; then
  rm -f "${IMPORT_FILE}"
fi

jq -c '.[]' "${TEAMS_FILE}" | while read -r team; do
  TEAM_NAME=$(echo "${team}" | jq -r '.name')
  TEAM_ID=$(echo "${team}" | jq -r '.id')
  TEAM_SLUG=$(echo "${team}" | jq -r '.slug')
  TERRAFORM_RESOURCE_NAME=$(echo "${TEAM_NAME}" | tr '[:upper:]' '[:lower:]' | sed 's/[-\.]/_/g')
  TERRAFORM_TEAM_FILE=/opt/resources/teams/"${TERRAFORM_RESOURCE_NAME}".tf

  team=$(curl -sSL \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${GITHUB_ACCESS_TOKEN}" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "${API_URL_PREFIX}/orgs/${ORG}/teams/${TEAM_NAME}")

  echo ">> Converting ${TEAM_NAME} team to Terraform resource (teams/${TERRAFORM_RESOURCE_NAME}.tf)..."

  TERRAFORM_RESOURCE_NAME=${TERRAFORM_RESOURCE_NAME} \
  TEAM_NAME=${TEAM_NAME} \
  TEAM_DESCRIPTION=$(echo "${team}" | jq '.description // ""') \
  TEAM_PRIVACY=$(echo "${team}" | jq -r '.privacy // "secret"') \
  TEAM_PARENT_ID=$(echo "${team}" | jq -r '.parent.id // null') \
  envsubst < /opt/templates/github_team.template > "${TERRAFORM_TEAM_FILE}"
  echo "terraform import -var-file=main.tfvars module.members.github_team.${TERRAFORM_RESOURCE_NAME} ${TEAM_NAME}" >> "${IMPORT_FILE}"

  ID=${ID} \
  ORG=${ORG} \
  TEAM_ID=${TEAM_ID} \
  TEAM_SLUG=${TEAM_SLUG} \
  TERRAFORM_TEAM_FILE=${TERRAFORM_TEAM_FILE} \
  TERRAFORM_TEAM_RESOURCE_NAME=${TERRAFORM_RESOURCE_NAME} \
  GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} \
  API_URL_PREFIX=${API_URL_PREFIX} \
  convert-team-members-to-resources

  ID=${ID} \
  ORG=${ORG} \
  TEAM_ID=${TEAM_ID} \
  TEAM_SLUG=${TEAM_SLUG} \
  TERRAFORM_TEAM_FILE=${TERRAFORM_TEAM_FILE} \
  TERRAFORM_TEAM_RESOURCE_NAME=${TERRAFORM_RESOURCE_NAME} \
  GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} \
  API_URL_PREFIX=${API_URL_PREFIX} \
  convert-team-repositories-to-resources
done
