#!/bin/bash
if [[ "${DEBUG}" == "true" ]]; then
  set -x
fi

ID=${ID:-''}
ID_DIR="/tmp/logs/${ID}"
ORG=${ORG:-''}
GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN:-''}
API_URL_PREFIX=${API_URL_PREFIX:-'https://api.github.com'}
MEMBERS_FILE="${ID_DIR}/members.json"
IMPORT_FILE=/opt/resources/imports_members.txt

if [ -f "${IMPORT_FILE}" ]; then
  rm -f "${IMPORT_FILE}"
fi

jq -c '.[]' "${MEMBERS_FILE}" | while read -r member; do
  MEMBER_LOGIN=$(echo "${member}" | jq -r '.login')
  TERRAFORM_RESOURCE_NAME=$(echo "${MEMBER_LOGIN}" | tr '[:upper:]' '[:lower:]' | sed 's/[-\.]/_/g')

  echo ">> Converting ${MEMBER_LOGIN} member to Terraform resource (members/${TERRAFORM_RESOURCE_NAME}.tf)..."

  membership=$(curl -sSL \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${GITHUB_ACCESS_TOKEN}" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "${API_URL_PREFIX}/orgs/${ORG}/memberships/${MEMBER_LOGIN}")

  TERRAFORM_RESOURCE_NAME=${TERRAFORM_RESOURCE_NAME} \
  MEMBERSHIP_USERNAME=${MEMBER_LOGIN} \
  MEMBERSHIP_ROLE=$(echo "${membership}" | jq -r '.role // "member"') \
  envsubst < /opt/templates/github_membership.template > /opt/resources/members/"${TERRAFORM_RESOURCE_NAME}".tf

  echo "terraform import -var-file=main.tfvars module.members.github_membership.${TERRAFORM_RESOURCE_NAME} ${ORG}:${MEMBER_LOGIN}" >> "${IMPORT_FILE}"
done
