#!/bin/bash
if [[ "${DEBUG}" == "true" ]]; then
  set -x
fi

ID=${ID:-''}
ID_DIR="/tmp/logs/${ID}"
mkdir -p "${ID_DIR}"
mkdir -p "${ID_DIR}/teams"
echo "Starting to get teams... (ID=${ID})"

ORG=${ORG:-''}
GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN:-''}
API_URL_PREFIX=${API_URL_PREFIX:-'https://api.github.com'}

page=1
has_more=true
while [ "$has_more" = true ]; do
  teams=$(curl -sSL \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${GITHUB_ACCESS_TOKEN}" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "${API_URL_PREFIX}/orgs/${ORG}/teams?per_page=100&page=${page}")

  if [ "$(echo "${teams}" | jq 'length')" -eq 0 ]; then
    has_more=false
  else
    echo "${teams}" > "${ID_DIR}/teams/page_${page}.json"
    ((page++))
  fi
done

jq -s '.[]' "${ID_DIR}"/teams/*.json > "${ID_DIR}/teams.json"
ID=${ID} ORG=${ORG} GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} convert-teams-to-resources
